config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from to_do_list import views
from config.views import welcomeFoydalanuvchi

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include("to_do_list.urls")),

    #================================================
    path('', include("accounts.urls")),

    path('', welcomeFoydalanuvchi, name='welcomeFoydalanuvchi'),
    
    # =================================================
    
]

to_do_list/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path("createVazifa/", views.createVazifa, name="createVazifa"),
    path("readVazifa/", views.readVazifa, name="readVazifa"),
    path("readVazifa/<int:idMe>/", views.detailVazifa, name="detailVazifa"),
    path("readVazifa/<int:idMe>/update/", views.updateVazifa, name='updateVazifa'),
    path("readVazifa/<int:idMe>/delete/", views.deleteVazifa, name='deleteVazifa'),
    
    path("historyVazifa/", views.historyVazifa, name='historyVazifa'),
    path("historyDeleteDate/<int:idMe>/", views.historyDeleteDate, name='historyDeleteDate'),
    path("progress/", views.progress, name='progress'),


    path("bajarilganVazifalar/<int:idMe>/", views.bajarilganVazifalar, name='bajarilganVazifalar'),
    path("unBajarilganVazifalar/<int:idMe>/", views.unBajarilganVazifalar, name='unBajarilganVazifalar'),
    
    path("readVazifa/<int:idMe>/bajarildiVazifa/", views.bajarildiVazifa, name='bajarildiVazifa'),

    
    
    




    #==========================================

 


    #==========================================
]

to_do_list/models.py
from django.db import models
from django.utils.timezone import now
from datetime import time

from django.contrib.auth.models import User

class DateBajarildiModel(models.Model):
    foydalanuvchi = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField()

    def __str__(self):
        return self.date.strftime("%Y-%m-%d")
    
    class Meta:
        ordering = ['date']
    
class VazifaModel(models.Model):
    foydalanuvchi = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    sarlavha = models.CharField(verbose_name="vazifa", max_length=200)
    tuliq_malumot = models.TextField()
    boshlanish_vaqti = models.TimeField(null=True, blank=True)
    tugatish_muddati = models.TimeField(null=True, blank=True)
    bajarilgan_date = models.ForeignKey(DateBajarildiModel, on_delete=models.CASCADE, null=True, blank=True)
    bajarilgan_vaqt =  models.TimeField(null=True, blank=True)
    bajarildi = models.BooleanField(default=False)
    
    def __str__(self):
        return self.sarlavha
    


    

to_do_list/forms.py
from django import forms
from .models import VazifaModel, DateBajarildiModel
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils import timezone




class VazifaPostForm(forms.ModelForm):
    input_date = forms.DateField(
        label='Select a Date',
        widget=forms.DateInput(attrs={'type': 'date'}),
    )
   
        

    #===========================

    challenge = forms.ChoiceField(label='Challenge', choices=[])

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['input_date'].initial = timezone.localdate()
        
        self.fields['challenge'].choices = self.get_challenge_choices()

    def get_challenge_choices(self):
        # Retrieve choices dynamically from a data source
        # For example, from a database query or API call
        days_of_month = [(str(day), f"{day} kun challenge") for day in range(1, 32)]
        return days_of_month

    
    


    class Meta:
        model = VazifaModel
        fields = ["sarlavha", "tuliq_malumot", 'input_date', 'challenge', 'boshlanish_vaqti', "tugatish_muddati", 'bajarildi']
        widgets = {
            'boshlanish_vaqti': forms.TimeInput(attrs={'type': 'time'}),
            'tugatish_muddati': forms.TimeInput(attrs={'type': 'time'}),
            
        }




#=================================================================================




    

to_do_list/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from datetime import date, datetime, timedelta
from itertools import groupby
from operator import itemgetter
import json
from django.db.models import Q




from django.contrib.admin.views.decorators import staff_member_required
from .models import VazifaModel, DateBajarildiModel
from .forms import VazifaPostForm






#=====================================================================================
@login_required
def readVazifa(request): #list of activities
    # __gt = Filter the to-do items where the due date is greater than the current datetime
    current_time = timezone.localtime().time()
    current_date = timezone.localdate().strftime('%Y-%m-%d')

    filter1 = Q(
        bajarilgan_date__date__gt=current_date,
        foydalanuvchi=request.user,
        bajarildi=False)
    
    
    # __gt = Filter the to-do items where the due date is greater than the current datetime
    filter2 = Q(
        tugatish_muddati__gt=current_time,
        bajarilgan_date__date=current_date,
        foydalanuvchi=request.user,
        bajarildi=False)
    
    merged_filter = filter1 | filter2

    modelMe = VazifaModel.objects.filter(merged_filter).order_by('bajarilgan_date__date', 'boshlanish_vaqti')
    
    
    current_time = timezone.localtime().time()
    current_date = timezone.localdate().strftime('%Y-%m-%d')
    for index, vazifa in enumerate(modelMe[:]):
        if vazifa.tugatish_muddati <= current_time and vazifa.bajarilgan_date.date.strftime('%Y-%m-%d') == current_date:
            del modelMe[index]
    
    print(modelMe)
    # Create a list to store the grouped to-do items and date headings
    dateMe = timezone.localdate()
    grouped_items = []
    for date, vazifalar in groupby(modelMe, key=lambda x: x.bajarilgan_date):
        boo = f'{dateMe}' == f'{date}'
        grouped_items.append({
            'vazifa_kuni': date,
            'vazifalar': sorted(vazifalar, key=lambda vazifa: vazifa.boshlanish_vaqti),
            'dat': boo,
        })
        
    return render(request, "to_do_list/readVazifa.html", {"modelMe": grouped_items, 
                                                          'timeMe': timezone.localtime().time(),
                                                          'dateMe': timezone.localdate().strftime('%Y-%m-%d'),
                                                          })

#=================================================================================
# CRDU

@login_required
def createVazifa(request):
    if request.method == 'POST':
        formMe =  VazifaPostForm(request.POST)
        if formMe.is_valid():
            input_date = formMe.cleaned_data['input_date']
            challenge = int(formMe.cleaned_data['challenge'])
            vazifas = []
            for i in range(challenge):
                vazifa_kuni, created = DateBajarildiModel.objects.get_or_create(date=input_date + timedelta(days=i), foydalanuvchi=request.user)
                vazifa = VazifaModel(
                    foydalanuvchi = request.user,
                    sarlavha=formMe.cleaned_data['sarlavha'],
                    tuliq_malumot=formMe.cleaned_data['tuliq_malumot'],
                    bajarilgan_date = vazifa_kuni,
                    boshlanish_vaqti=formMe.cleaned_data['boshlanish_vaqti'],
                    tugatish_muddati=formMe.cleaned_data['tugatish_muddati'],
                )
                vazifas.append(vazifa)
                
            VazifaModel.objects.bulk_create(vazifas)
            return redirect("readVazifa")
    else:
        formMe =  VazifaPostForm()
    return render(request, 'to_do_list/createVazifa.html', {'formMe': formMe})
 
@login_required
def detailVazifa(request, idMe):
    objMe = get_object_or_404(VazifaModel, id=idMe)
    print(objMe.bajarilgan_date)
    if request.user.is_authenticated:
        return render(request, "to_do_list/detailVazifa.html", {"objMe": objMe})
    else:
        return redirect("readVazifa")

@login_required
def updateVazifa(request, idMe):
    objVazifa = get_object_or_404(VazifaModel, id=idMe)
    if request.method == 'POST':
        formMe =  VazifaPostForm(request.POST, instance=objVazifa)
        if formMe.is_valid():
            formMe.save()
            return redirect('readVazifa')
                
            
    else:
        formMe =  VazifaPostForm(instance=objVazifa)
    return render(request, 'to_do_list/updateVazifa.html', {'formMe': formMe})

@login_required 
def deleteVazifa(request, idMe):
    objMe = get_object_or_404(VazifaModel, id=idMe)
    objMe.delete()
    return redirect("readVazifa")

#===========================

# History request
def historyVazifa(request):
    date_now = timezone.localdate()
    modelMe = DateBajarildiModel.objects.filter(
        date__lte = date_now,
        foydalanuvchi=request.user,
    ).values() # historyVazifalar

    last_10kun = date_now - timezone.timedelta(days=10)
    # Delete older records for non-staff users
    if not request.user.is_staff:
        DateBajarildiModel.objects.filter(
            date__lt=last_10kun,
            foydalanuvchi=request.user
        ).delete()
    dat = []
    for item in modelMe:
        item['date'] = item['date'].strftime("%Y-%m-%d")
        dat.append(item)
    return render(request, "to_do_list/historyVazifa.html", {"modelMe": dat})


# delete History Date
def historyDeleteDate(request, idMe):
    objMe = get_object_or_404(DateBajarildiModel, id=idMe)
    objMe.delete()
    return redirect("historyVazifa")

# time difference without request
def calculate_time_difference(boshlanish_vaqti, bajarilgan_vaqt):
    boshlanish_vaqti = datetime.combine(timezone.localdate(), boshlanish_vaqti)
    bajarilgan_vaqt = datetime.combine(timezone.localdate(), bajarilgan_vaqt)
    time_difference = bajarilgan_vaqt - boshlanish_vaqti
    print("TIME DIFFERENCE:",time_difference)
    total_hours = time_difference.total_seconds() // 3600  # Calculate total hours
    total_minutes = (time_difference.total_seconds() % 3600) / 60  # Calculate remaining minutes

    total_decimal = total_hours + (total_minutes / 60)  # Convert minutes to decimal part

    return total_decimal

# progress
def progress(request):
    date_now = timezone.localdate()
    kunlar = DateBajarildiModel.objects.filter(
        date__lte = date_now,
        foydalanuvchi=request.user,
    ) # historyVazifalar
    last_10kun = date_now - timezone.timedelta(days=10)
    # Delete older records for non-staff users
    if not request.user.is_staff:
        DateBajarildiModel.objects.filter(
            date__lt=last_10kun,
            foydalanuvchi=request.user
        ).delete()

    print(kunlar)
    bajarilgan_by_date = {}
    vazifalar = []
    for record in kunlar:
        suralgan_date = record
        print(suralgan_date, "suralgan122")

        vazifalar = VazifaModel.objects.filter(
            bajarilgan_date=suralgan_date,
            foydalanuvchi=request.user,
            bajarildi=True
        ).values()
        print(vazifalar)
        
        converted_queryset = []
        for object in vazifalar:
            print('bajarildi:',object['bajarildi'])
            boshlanish_vaqti_str = object['boshlanish_vaqti']
            bajarilgan_vaqt_str = object['bajarilgan_vaqt']
            print("Boshlanish vaqti:", boshlanish_vaqti_str)
            print("Bajarilgan vaqt:", bajarilgan_vaqt_str)

            float = calculate_time_difference( boshlanish_vaqti_str, bajarilgan_vaqt_str)
            print("float:",float)
            converted_queryset.append(float)
            print(converted_queryset)
         

        bajarilgan_by_date[suralgan_date.date.strftime('%Y-%m-%d')] = sum(converted_queryset)
    print(bajarilgan_by_date)
    data_json = json.dumps(bajarilgan_by_date)
    print(data_json)
    
    return render(request, "to_do_list/progress.html", {'data_json': data_json})






#==========================================================
# Done and Undone
@login_required
def bajarilganVazifalar(request, idMe):
    suralgan_date = get_object_or_404(DateBajarildiModel, id=idMe)
    bajarilgan = VazifaModel.objects.filter(
        bajarilgan_date=suralgan_date, 
        foydalanuvchi=request.user, 
        bajarildi=True).values()
    return render(request, "to_do_list/filteredHistoryVazifalar.html", {"bajarilgan": bajarilgan,
                                                                        'idMe': idMe,
                                                                        'len_bajarilgan': len(bajarilgan),
                                                                        'suralgan_date': suralgan_date})
                                                                        
    
# __lte = Filter the to-do items where the due date is before or equal to the current datetime
@login_required
def unBajarilganVazifalar(request, idMe):
    suralgan_date = get_object_or_404(DateBajarildiModel, id=idMe)
    unBajarilgan = VazifaModel.objects.filter(
        tugatish_muddati__lte=timezone.localtime().time(),
        bajarilgan_date__date__lte=timezone.localdate(),
        bajarilgan_date=suralgan_date, 
        foydalanuvchi=request.user, 
        bajarildi=False).values()
    return render(request, "to_do_list/filteredHistoryVazifalar.html", {"unBajarilgan": unBajarilgan, 'idMe': idMe, 'len_unBajarilgan': len(unBajarilgan)})


# =============================
# Mark the Vazifa done

def bajarildiVazifa(request, idMe):
    objVazifa = get_object_or_404(VazifaModel, id=idMe)
    objVazifa.bajarildi = True
    objVazifa.bajarilgan_vaqt = timezone.localtime().time()
    objVazifa.bajarilgan_date, created = DateBajarildiModel.objects.get_or_create(date=timezone.localdate(),

to_do_list/templates/to_do_list/authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The authors</title>
</head>
<body>
    <h1></h1>
</body>
</html>

to_do_list/templates/to_do_list/bajarilganVazifalar.html
<!DOCTYPE html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vazifalar Ro'yxati</title>
    <!-- Add Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'to_do_list/read_style.css' %}">
    <!-- Custom Styles -->
    <style>
        /* *{
            border: 1px solid red;
        } */
        .done_undone {
            display: flex;
            justify-content: center;
            align-items: flex-end; /* Align items to the bottom of the container */
            margin-top: 10px; /* Adjust the margin as needed */
        }
        
        .done_undone a {
            color: #fff;
            text-decoration: none;
            padding: 10px 20px;
            font-size: 18px;
            transition: background-color 0.3s; /* Add a transition effect for smoother hover */
        }
        
        .done_undone a:first-child {
            background-color: #4caf50; /* Green background for "Done" link */
            border-top-left-radius: 5px;
            border-bottom-left-radius: 5px;
        }
        
        .done_undone a:last-child {
            background-color: #4caf50; /* White background for "Undone" link */
            border-top-right-radius: 5px;
            border-bottom-right-radius: 5px;
        }
        
        .done_undone a:hover {
            background-color: #87a988; /* Darker background when hovering */
        }
    </style>
    
    
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">
                <span class="logo-icon"><i class="fa fa-check-circle"></i></span>
                To-do App
            </a>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'readVazifa' %}"><i class="fa fa-list-ul"></i> To-do</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/bajarilganVazifalar/"><i class="fa fa-tasks"></i> Progress</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fa fa-user"></i> Profile</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="done_undone">
        <a href="{% url 'unBajarilganVazifalar' %}">Undone</a>
        <a href="{% url 'bajarilganVazifalar' %}">Done</a>
    </div>

    <div class="cool-background">
        <div class="circle circle-green"></div>
        <div class="circle circle-white"></div>
        <div class="circle circle-green-2"></div>
        <div class="circle circle-white-2"></div>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="card">
                <div class="card-header">
                    <h2>Bajarilgan Vazifalar</h2>
                </div>
                <div class="card-body">
                    <div class="task-list">
                        {% for i in modelMe %}

                        
                        <div class="item">

                            <div class="chec">
                                <i class="fa fa-check-circle"></i>
                            </div>

                            <div class="task-item">
                                <h1><strong>{{ i.sarlavha }}</strong></h1>
                                <p>{{ i.tuliq_malumot }}</p>
                                <h5>Bajarilgan_vaqt{{ i.bajarilgan_vaqt }}</h5>
                            </div>
                        </div>

                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Add Bootstrap JS and jQuery -->
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> -->
</body> 
</html>

to_do_list/templates/to_do_list/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->

    <title>{% block headme%} {% endblock%}</title>
  </head>
  <body>
    <div class="container-fluid">
      {% block contentme %}
      {% endblock %} 
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

to_do_list/templates/to_do_list/createVazifa.html
{% extends 'to_do_list/layout.html'%}
{% load django_bootstrap5 %}
{% load static %}
    {% block title %} Vazifa Yaratish {% endblock %}
    {% block head %} 
        <link rel="stylesheet" href="{% static 'to_do_list/read_style.css' %}">
        <style>
            .form input[type="checkbox"]{
                display: none;
            }
            .form-check-label{
                display: none;
            }
            label[for="id_boshlanish_vaqti"], label[for="id_tugatish_muddati"]{
                display: inline;
            }
        </style>
    {% endblock %}

    {% block content %}
    <div class="container">
        <div class="row justify-content-center">

            <!-- Create To-Do Form -->
            <div class="card">
                <div class="card-header">
                    <h2>Vazifa yaratish</h2>
                </div>
                <div class="row my-5">
                    <div class="col-md-12">
                <div class="card-body">
                    <form method="post" action="{% url 'createVazifa' %}" class="form">

                        {% bootstrap_form formMe %}
                        {% csrf_token %}

                        
                        
                        <button type="submit" class="btn btn-block"><strong>Vazifani yaratish</strong></button>
                    </form>
                </div>
            </div>
            </div>
            </div>
        </div>
    </div>
    {% endblock %}

to_do_list/templates/to_do_list/detailVazifa.html
{% extends "to_do_list/base.html" %}
{% block contentme %}

<h1>{{objMe.sarlavha}}</h1>
<p>{{objMe.tuliq_malumot}}</p>
<p>{{objMe.tugatish_muddati}}</p>
<p>Bajarildi:{{objMe.bajarildi}}</p>


{% endblock %}

to_do_list/templates/to_do_list/filteredHistoryVazifalar.html
{% extends 'to_do_list/layout.html' %}
{% block title %} Filter {% endblock %}
{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'to_do_list/filterHistory.css' %}">
    <style>
        
    </style>
{% endblock %}
{% block content %}
    <div class="container justify-content-center card-body" id="done_undone">
        <div class="row">
            <div class="col done">
                <form action="{% url 'bajarilganVazifalar' idMe %}" method="get" class="done">
                    <button type="submit" class="btn" style="color: aliceblue;">Bajarilgan</button>
                </form>
            </div>
            <div class="col undone">
                <form action="{% url 'unBajarilganVazifalar' idMe %}" method="get" class="undone">
                    <button type="submit" class="btn" style="color: azure;">Bajarilmagan</button>
                </form>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="card">
                {% if bajarilgan %}
                <div class="card-header">
                    <h2><strong>Bajarilgan vazifalar ({{len_bajarilgan}})</strong></h2>
                </div>
                {% endif %}
                {% if unBajarilgan %}
                <div class="card-header">
                    <h2>Bajarilgmagan vazifalar ({{len_unBajarilgan}})</h2>
                </div>
                {% endif %}
                <div class="card-body">
                    <div class="task-list">
                        {% for i in bajarilgan %}
                        
                        <div class="item">

                            <div class="check check-green">
                                <i class="fa fa-check-circle"></i>
                            </div>

                            <div class="task-item">
                                <h1><strong>{{ i.sarlavha }}</strong></h1>
                                <p>{{ i.tuliq_malumot }}</p>
                                <h5>Boshlash vaqti: {{ i.boshlanish_vaqti|time:"H:i:s" }}</h5>
                                <h5>Tugatish vaqti: {{ i.tugatish_muddati|time:"H:i:s" }}</h5><br>
                                <h5>Tugatilgan vaqt: {{ i.bajarilgan_vaqt|time:"H:i:s" }}</h5>
                                
                                <div class="edit_del">
                                    <form action="{% url 'updateVazifa' i.id %}">
                                        {% csrf_token %}
                                        <button class="btn"><i class="fa fa-edit" style="color: aliceblue;"></i></button>
                                    </form>
                                    <form action="{% url 'deleteVazifa' i.id %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="btn del"><i class="fa fa-trash" style="color: aliceblue;"></i></button>
                                    </form>
                                </div>

                            </div>
                        </div>

                        {% endfor %}

                        <!-- For Undone Tasks -->
                        {% for i in unBajarilgan %}
                        <div class="item">

                            <div class="check check-red">
                                <i class="fa fa-times-circle"></i>
                            </div>

                            <div class="task-item">
                                <h1><strong>{{ i.sarlavha }}</strong></h1>
                                <p>{{ i.tuliq_malumot }}</p>
                                <h5>Boshlash vaqti: {{ i.boshlanish_vaqti|time:"H:i:s" }}</h5>
                                <h5>Tugatish vaqti: {{ i.tugatish_muddati|time:"H:i:s" }}</h5>
                                
                                <div class="edit_del">
                                    <form action="{% url 'updateVazifa' i.id %}">
                                        {% csrf_token %}
                                        <button class="btn"><i class="fa fa-edit"></i></button>
                                    </form>
                                    <form action="{% url 'deleteVazifa' i.id %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="btn del"><i class="fa fa-trash"></i></button>
                                    </form>
                                </div>

                            </div>
                        </div>

                        {% endfor %}


                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const buttons = document.querySelectorAll(".btn");
    
            buttons.forEach(button => {
                button.addEventListener("click", function () {
                    buttons.forEach(btn => btn.classList.remove("active"));
                    this.classList.add("active");
                });
            });
        });
    </script>

{% endblock %}

to_do_list/templates/to_do_list/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
        {% for i in nomi%}
        <li><h1>{{i.sarlavha}}</h1>{{i.tuliq_malumot}}<br>{{i.tugatish_muddati}}</li>
        {% endfor %}
    </ul>
</body>
</html>

to_do_list/templates/to_do_list/updateVazifa.html
{% extends 'to_do_list/layout.html' %}
{% load django_bootstrap5 %}
{% block title %}Vazifani O'zgartirish {%endblock%}
{% load static %}
{% block head %} 
    <link rel="stylesheet" href="{% static 'to_do_list/read_style.css' %}">
    <style>
        .form input[type="checkbox"]{
            display: none;
        }
        .form-check-label{
            display: none;
        }
        label[for="id_boshlanish_vaqti"], label[for="id_tugatish_muddati"]{
            display: inline;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <!-- Create To-Do Form -->
            <div class="card">
                <div class="card-header">
                    <h2>Vazifaga o'zgartirish kiritish<h2>
                </div>
                <div class="card-body">
                    <form method="post" action="." class="form">
                        {% csrf_token %}
                        <!-- Title Field -->
                        <!-- <div class="form-group">
                            <label for="{{ formMe.sarlavha.id_for_label }}">Sarlavha</label> -->
                            {% bootstrap_form formMe %}
                            {% if formMe.sarlavha.errors %}
                                <p class="error-message">{{ formMe.sarlavha.errors }}</p>
                            {% endif %}
                        <!-- </div>   -->
                        <!-- Description Field -->
                        <!-- <div class="form-group">
                            <label for="{{ formMe.tuliq_malumot.id_for_label }}">Tavsif</label> -->
                            <!-- {% bootstrap_form formMe %} -->
                            {% if formMe.tuliq_malumot.errors %}
                                <p class="error-message">{{ formMe.tuliq_malumot.errors }}</p>
                            {% endif %}
                        <!-- </div> -->
                        
                        <!-- Todo date -->
                        <!-- <div class="form-group">
                            <label for="{{ formMe.input_date.id_for_label }}">Vazifa kuni</label> -->
                            <!-- {% bootstrap_form formMe %} -->
                            {% if formMe.input_date.errors %}
                                <p class="error-message">{{ formMe.input_date.errors }}</p>
                            {% endif %}
                        <!-- </div> -->

                        <!-- Start Field -->
                        <!-- <div class="form-group">
                            <label for="{{ formMe.boshlanish_vaqti.id_for_label }}">Boshlanish vaqti</label> -->
                            <!-- {% bootstrap_form formMe %} -->
                            {% if formMe.boshlanish_vaqti.errors %}
                                <p class="error-message">{{ formMe.boshlanish_vaqti.errors }}</p>
                            {% endif %}
                        <!-- </div> -->

                        

                        <!-- Deadline Field -->
                        <!-- <div class="form-group">
                            <label for="{{ formMe.tugatish_muddati.id_for_label }}">Tugatish muddati</label> -->
                            <!-- {% bootstrap_form formMe %} -->
                            {% if formMe.tugatish_muddati.errors %}
                                <p class="error-message">{{ formMe.tugatish_muddati.errors }}</p>
                            {% endif %}
                        <!-- </div> -->
                            
                        
                        <button type="submit" class="btn btn-block"><strong>O'zgartirish</strong></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}